// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.DBModels;

namespace StudentManager.DBModels.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230602020039_AlterStudentTableData_2")]
    partial class AlterStudentTableData_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentManager.DBModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassName");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = 2,
                            Email = "kongchuiliang@126.com",
                            Name = "孔垂良"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = 1,
                            Email = "caoyan@126.com",
                            Name = "曹燕"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = 1,
                            Email = "kongyoujia@126.com",
                            Name = "孔佑嘉"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
